KatanaNativeInterface: KNI_MHF Namespace Reference
KNI_MHF Namespace Reference
Classes
struct unary_precalc_sin
function-object which calculates sinus for n-elements of a container if used together with a STL algorithm
struct unary_precalc_cos
See also:
unary_precalc_sin
struct unary_rad2deg
a function-object version of rad2deg
struct unary_deg2rad
a function-object version of rad2deg
Functions
template<typename _T>
short sign (_T x)
template<typename _T>
_T atan1 (_T in1, _T in2)
template<typename _T>
_T acotan (const _T in)
template<typename _T>
_T atan0 (const _T in1, const _T in2)
template<typename _T>
_T pow2 (const _T in)
template<typename _T>
_T rad2deg (const _T a)
conversion from radian to degree
template<typename _T>
_T deg2rad (const _T a)
conversion from degree to radian
template<typename _T>
_T anglereduce (const _T a)
template<typename _angleT, typename _encT>
_encT rad2enc (_angleT const &angle, _angleT const &angleOffset, _encT const &epc, _encT const &encOffset, _encT const &rotDir)
converts absolute angles in radian to encoders.
template<typename _angleT, typename _encT>
_angleT enc2rad (_encT const &enc, _angleT const &angleOffset, _encT const &epc, _encT const &encOffset, _encT const &rotDir)
converts encoders to absolute angles in radian
double findFirstEqualAngle (double cosValue, double sinValue, double tolerance)
Find the first equal angle.
Function Documentation
template<typename _T> _T KNI_MHF::acotan (const _T in) [inline]
Definition at line 77 of file MathHelperFunctions.h.
References M_PI.
template<typename _T> _T KNI_MHF::anglereduce (const _T a) [inline]
Definition at line 126 of file MathHelperFunctions.h.
References M_PI.
Referenced by findFirstEqualAngle().
template<typename _T> _T KNI_MHF::atan0 (const _T in1, const _T in2) [inline]
Definition at line 85 of file MathHelperFunctions.h.
References M_PI.
template<typename _T> _T KNI_MHF::atan1 (_T in1, _T in2) [inline]
Definition at line 62 of file MathHelperFunctions.h.
References M_PI, and sign().
template<typename _T> _T KNI_MHF::deg2rad (const _T a) [inline]
conversion from degree to radian
Definition at line 114 of file MathHelperFunctions.h.
References M_PI.
Referenced by KNI_MHF::unary_deg2rad< _T >::operator()().
template<typename _angleT, typename _encT> _angleT KNI_MHF::enc2rad (_encT const & enc, _angleT const & angleOffset, _encT const & epc, _encT const & encOffset, _encT const & rotDir) [inline]
converts encoders to absolute angles in radian
Definition at line 148 of file MathHelperFunctions.h.
References M_PI.
double KNI_MHF::findFirstEqualAngle (double cosValue, double sinValue, double tolerance) [inline]
Find the first equal angle.
You have to pass a cos and a sin Value
Definition at line 157 of file MathHelperFunctions.h.
References anglereduce(), and M_PI.
template<typename _T> _T KNI_MHF::pow2 (const _T in) [inline]
Definition at line 92 of file MathHelperFunctions.h.
template<typename _T> _T KNI_MHF::rad2deg (const _T a) [inline]
conversion from radian to degree
Definition at line 100 of file MathHelperFunctions.h.
References M_PI.
Referenced by KNI_MHF::unary_rad2deg< _T >::operator()().
template<typename _angleT, typename _encT> _encT KNI_MHF::rad2enc (_angleT const & angle, _angleT const & angleOffset, _encT const & epc, _encT const & encOffset, _encT const & rotDir) [inline]
converts absolute angles in radian to encoders.
Definition at line 134 of file MathHelperFunctions.h.
References M_PI.
template<typename _T> short KNI_MHF::sign (_T x) [inline]
Definition at line 37 of file MathHelperFunctions.h.
Referenced by atan1().