######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 5 08:10:35 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . inc src
INCLUDEPATH += . inc ../../include ../common
LIBS += -L../../lib/linux -L../common -lKNIBase -lKNI_InvKin -lKNI_LM

# Input
HEADERS += inc/BurnInTestWindow.h
SOURCES += main.cpp src/BurnInTest.cpp src/BurnInTestWindow.cpp
